pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Start') {
            steps {
                echo 'Starting the Maven Build to fix a bug!'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
        stage('Complete') { 
            steps {
                echo 'Build and Test Completed for a bug fix!' 
            }
        }
    }
}
